version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # Expose the app on port 3001 change if needed
    environment:
      - NODE_ENV=production
      - THERMOSTAT_ID=your_thermostat_id # Replace with your actual thermostat ID
      - LOG_LEVEL=info
    volumes:
      - ./logs:/usr/src/app/logs
      - ./resource:/usr/src/app/resource
    command: ["npm", "run", "start"]
