version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3001:3000" # Expose the app on port 3001 change if needed
        environment:
            - NODE_ENV=production
            - LOG_LEVEL=info
            - SECRET_KEY=${SECRET_KEY} # Replace with your actual secret key
        volumes:
            - ./logs:/usr/src/app/logs
            - ./resource:/usr/src/app/resource
        command: ["npm", "run", "start"]
